//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Portfolio.Core.Models
{
	/// <summary>CV</summary>
	[PublishedModel("cV")]
	public partial class CV : PublishedContentModel, IWorkHistoryControls
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		public new const string ModelTypeAlias = "cV";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<CV, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public CV(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Contact Info: Enter the contact info
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		[ImplementPropertyType("contactInfo")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedElement> ContactInfo => global::Portfolio.Core.Models.WorkHistoryControls.GetContactInfo(this, _publishedValueFallback);

		///<summary>
		/// Contact Info Title: Enter the title for the contact info section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		[ImplementPropertyType("contactInfoTitle")]
		public virtual string ContactInfoTitle => global::Portfolio.Core.Models.WorkHistoryControls.GetContactInfoTitle(this, _publishedValueFallback);

		///<summary>
		/// Education History: Enter the details of your education
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		[ImplementPropertyType("educationHistory")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Portfolio.Core.Models.HistoryItem> EducationHistory => global::Portfolio.Core.Models.WorkHistoryControls.GetEducationHistory(this, _publishedValueFallback);

		///<summary>
		/// Education History Title: Enter the title for the education history section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		[ImplementPropertyType("educationHistoryTitle")]
		public virtual string EducationHistoryTitle => global::Portfolio.Core.Models.WorkHistoryControls.GetEducationHistoryTitle(this, _publishedValueFallback);

		///<summary>
		/// Hobbies: Enter the content for the hobbies section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		[ImplementPropertyType("hobbies")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Hobbies => global::Portfolio.Core.Models.WorkHistoryControls.GetHobbies(this, _publishedValueFallback);

		///<summary>
		/// Hobbies Title: Enter a title for the hobbies section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		[ImplementPropertyType("hobbiesTitle")]
		public virtual string HobbiesTitle => global::Portfolio.Core.Models.WorkHistoryControls.GetHobbiesTitle(this, _publishedValueFallback);

		///<summary>
		/// Skills: Enter your skills and ratings
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		[ImplementPropertyType("skills")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Portfolio.Core.Models.SkillItem> Skills => global::Portfolio.Core.Models.WorkHistoryControls.GetSkills(this, _publishedValueFallback);

		///<summary>
		/// Skills Title: Enter the title for the skills section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		[ImplementPropertyType("skillsTitle")]
		public virtual string SkillsTitle => global::Portfolio.Core.Models.WorkHistoryControls.GetSkillsTitle(this, _publishedValueFallback);

		///<summary>
		/// Work History
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		[ImplementPropertyType("workHistory")]
		public virtual global::System.Collections.Generic.IEnumerable<global::Portfolio.Core.Models.HistoryItem> WorkHistory => global::Portfolio.Core.Models.WorkHistoryControls.GetWorkHistory(this, _publishedValueFallback);

		///<summary>
		/// Work History Title: Enter the title for the work history section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "9.0.0-rc003+36582f2cd2c6ddc797c85dac0a9a6572126bf602")]
		[ImplementPropertyType("workHistoryTitle")]
		public virtual string WorkHistoryTitle => global::Portfolio.Core.Models.WorkHistoryControls.GetWorkHistoryTitle(this, _publishedValueFallback);
	}
}
